spring:
  datasource:
    url: ENC(vJtBvCPKZo8ZK5nacUdmGE6mzSovD/awmboR1xfT8mLt99cm78eoGlcTxx+23aTcSb/3HXJLqMbOfVB7gNnRQoexCZlP+U6Ht+Jxzg79MMXTSyiKSScrlP7Wn27H1mpeuD8r9qrKsFQ=)
    username: ENC(97oTBNdqZE8wc1UJUa5+/g==)
    password: ENC(UVupbZkdKKNLSs5kbQy9D1G3CAWLzTzH)
    driver-class-name: ENC(McpdBFlqGYTqgxoSXpoYXrsFJ3YonHBDgM7/HBhhO0g=)

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: info

server:
  port: ENC(QEzGHdUxdfcigCOLkUvUsQ==)

file:
  thumbnail:
    path: ENC(kwagRPbW0/bQYOsQsuBjkF4ilciN9oR63tYvgyPdbQi0VI+GSfg9xA==)

log:
  config:
    path: ENC(2avk+SYIA4QtM9JWevyZHx5CzPgcqOF9jYPNqlz01tgZuXVGSuqo+A==)
    fileName: randomlunch
    errorFileName: randomlunch_error

logging:
  level:
    root: info
