spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/randomlunch
    username: sa
    password:
    driver-class-name: org.h2.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
#      https://stackoverflow.com/questions/65543131/spring-jpa-hibernate-ddl-auto-update-not-working-in-spring-boot
#      ddl-auto not working에 관련한 글
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug

server:
  port: 5069
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-type: PKCS12
    key-store-password: dla60177
    key-alias: bns-ssl



file:
  thumbnail:
    path: C://Users/MS/Desktop/목차/프로젝트/점심뭐먹지/picture/