spring:
  datasource:
    url: ENC(agr10QpFaRX+fxlGKdyIEp9xBmZsTzjWGSQuTJoxGa2N400H18+crXQEdnameKLp)
    username: ENC(gpwS31OV+13eF/h2lsDRHw==)
    password:
    driver-class-name: ENC(RZWV45PcNqTz+N3VaCK6FtxqClv/ldQ3)

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug

server:
  port: ENC(3uqt0kEpDqzMzaj7NEyLsQ==)

file:
  thumbnail:
    path: ENC(zuuePJIv5T3TNkkwE+Qov7RuPb97yh249MmYmrMPdmF4kXGXg1NHqMuMuHwuladRYaDIOMxzEQsT6KwAsqpFC/rJ3qdBaVYho10sgqJ62Zk=)

log:
  config:
    path: ENC(xA6NH4UdeXU/xzr4ErLRDpiDDct6j5Z3iJXe2fokJwNwspv9jFNAOdGDDwPZKzENexM3aZvkTwsrLr9pmt+7uqNUBoquY1U/)
    fileName: randomlunch
    errorFileName: randomlunch_error

logging:
  level:
    root: info
